"""Curated model catalog — the source of truth for what users can pick.

Each entry advertises capability, provider, pricing, context window, tier and
default-ness. Availability is computed at runtime by checking whether the
server has the matching API key configured (no per-user key entry needed —
Higgsfield-style).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

from helix.core.config import get_settings

Capability = Literal["chat", "image", "video", "embedding"]
Tier = Literal["free", "pro", "team"]


@dataclass(frozen=True)
class ModelSpec:
    id: str  # public id used by clients (e.g. "openai:gpt-4o-mini")
    provider: str  # "openai" | "anthropic" | "gemini" | "openrouter" | "replicate" | "runway" | "veo"
    model: str  # provider-native model name passed to the SDK
    display_name: str
    capability: Capability
    description: str
    context_window: int | None = None
    max_output_tokens: int | None = None
    input_price_per_1k: float = 0.0  # USD per 1k input tokens (chat) or per image (image)
    output_price_per_1k: float = 0.0  # USD per 1k output tokens
    price_per_image: float | None = None  # for image models
    price_per_second: float | None = None  # for video models
    tier: Tier = "pro"
    is_default: bool = False
    supports_streaming: bool = False
    supports_json_mode: bool = False
    supports_vision: bool = False
    tags: tuple[str, ...] = field(default_factory=tuple)
    requires_setting: str = ""  # name of Settings attr that must be truthy

    @property
    def settings_attr(self) -> str:
        if self.requires_setting:
            return self.requires_setting
        # default mapping
        return {
            "openai": "openai_api_key",
            "anthropic": "anthropic_api_key",
            "gemini": "gemini_api_key",
            "openrouter": "openrouter_api_key",
            "deepseek": "deepseek_api_key",
            "groq": "groq_api_key",
            "mistral": "mistral_api_key",
            "dashscope": "dashscope_api_key",
            "xai": "xai_api_key",
            "replicate": "replicate_api_token",
            "runway": "runway_api_key",
            "veo": "google_veo_api_key",
        }.get(self.provider, "")


# ---------------------------------------------------------------------------
# Chat models
# ---------------------------------------------------------------------------
_CHAT_MODELS: list[ModelSpec] = [
    # ── xAI Grok (latest flagship) ──────────────────────────────────────
    ModelSpec(
        id="xai:grok-4.3",
        provider="xai",
        model="grok-4.3",
        display_name="Grok 4.3",
        capability="chat",
        description="xAI's flagship Grok 4.3 model — peak agency, reasoning, SVG coding, and UX analysis.",
        context_window=250000,
        max_output_tokens=8192,
        input_price_per_1k=0.002,
        output_price_per_1k=0.01,
        tier="pro",
        supports_streaming=True,
        supports_json_mode=True,
        tags=("latest", "flagship", "reasoning", "grok"),
    ),
    ModelSpec(
        id="xai:grok-4.3-vision",
        provider="xai",
        model="grok-4.3-vision",
        display_name="Grok 4.3 Vision",
        capability="chat",
        description="Grok 4.3 with full multi-modal vision pipelines, ideal for wireframes and screenshot analysis.",
        context_window=250000,
        max_output_tokens=8192,
        input_price_per_1k=0.002,
        output_price_per_1k=0.01,
        tier="pro",
        supports_streaming=True,
        supports_json_mode=True,
        supports_vision=True,
        tags=("latest", "vision", "reasoning", "grok"),
    ),
    # ── xAI Grok via OpenRouter ──────────────────────────────────────────
    ModelSpec(
        id="openrouter:grok-4.3",
        provider="openrouter",
        model="x-ai/grok-4.3",
        display_name="Grok 4.3 (OpenRouter)",
        capability="chat",
        description="xAI Grok 4.3 via OpenRouter — ultra-powerful, no direct xAI key needed.",
        context_window=250000,
        max_output_tokens=8192,
        input_price_per_1k=0.002,
        output_price_per_1k=0.01,
        tier="pro",
        supports_streaming=True,
        supports_json_mode=True,
        tags=("xai", "latest", "flagship", "grok"),
    ),
    ModelSpec(
        id="openrouter:grok-4.3-vision",
        provider="openrouter",
        model="x-ai/grok-4.3-vision",
        display_name="Grok 4.3 Vision (OpenRouter)",
        capability="chat",
        description="xAI Grok 4.3 Vision via OpenRouter — flagship vision capabilities.",
        context_window=250000,
        max_output_tokens=8192,
        input_price_per_1k=0.002,
        output_price_per_1k=0.01,
        tier="pro",
        supports_streaming=True,
        supports_json_mode=True,
        supports_vision=True,
        tags=("xai", "latest", "vision", "grok"),
    ),
    # ── OpenAI (latest) ─────────────────────────────────────────────────
    ModelSpec(
        id="openai:gpt-5.5",
        provider="openai",
        model="gpt-5.5",
        display_name="GPT-5.5",
        capability="chat",
        description="OpenAI's absolute peak flagship — supreme professional knowledge work, complex coding, and autonomous tool use with 1M context.",
        context_window=1000000,
        max_output_tokens=64000,
        input_price_per_1k=0.00125,
        output_price_per_1k=0.01,
        tier="pro",
        supports_streaming=True,
        supports_json_mode=True,
        supports_vision=True,
        tags=("latest", "flagship", "vision", "reasoning"),
    ),
    ModelSpec(
        id="openai:gpt-5",
        provider="openai",
        model="gpt-5",
        display_name="GPT-5",
        capability="chat",
        description="OpenAI's legacy flagship — top reasoning, vision, and tool use.",
        context_window=400_000,
        max_output_tokens=32_000,
        input_price_per_1k=0.00125,
        output_price_per_1k=0.01,
        tier="pro",
        supports_streaming=True,
        supports_json_mode=True,
        supports_vision=True,
        tags=("legacy", "flagship", "vision", "reasoning"),
    ),
    ModelSpec(
        id="openai:gpt-5-mini",
        provider="openai",
        model="gpt-5-mini",
        display_name="GPT-5 mini",
        capability="chat",
        description="Newest small OpenAI model — fast, cheap, GPT-5-class quality.",
        context_window=400_000,
        max_output_tokens=32_000,
        input_price_per_1k=0.00025,
        output_price_per_1k=0.002,
        tier="free",
        is_default=True,
        supports_streaming=True,
        supports_json_mode=True,
        supports_vision=True,
        tags=("latest", "cheap", "fast", "default"),
    ),
    ModelSpec(
        id="openai:o3",
        provider="openai",
        model="o3",
        display_name="o3",
        capability="chat",
        description="OpenAI's deep-reasoning model — math, code, multi-step planning.",
        context_window=200_000,
        max_output_tokens=100_000,
        input_price_per_1k=0.002,
        output_price_per_1k=0.008,
        tier="pro",
        supports_streaming=True,
        supports_json_mode=True,
        tags=("latest", "reasoning", "deep-think"),
    ),
    ModelSpec(
        id="openai:o4-mini",
        provider="openai",
        model="o4-mini",
        display_name="o4 mini",
        capability="chat",
        description="Reasoning-tuned small model — cheap chain-of-thought.",
        context_window=200_000,
        max_output_tokens=100_000,
        input_price_per_1k=0.0011,
        output_price_per_1k=0.0044,
        tier="free",
        supports_streaming=True,
        supports_json_mode=True,
        tags=("latest", "reasoning", "cheap"),
    ),
    # ── OpenAI (legacy still supported) ─────────────────────────────────
    ModelSpec(
        id="openai:gpt-4o",
        provider="openai",
        model="gpt-4o",
        display_name="GPT-4o",
        capability="chat",
        description="Previous OpenAI flagship — still strong vision + JSON mode.",
        context_window=128_000,
        max_output_tokens=16_000,
        input_price_per_1k=0.0025,
        output_price_per_1k=0.01,
        tier="pro",
        supports_streaming=True,
        supports_json_mode=True,
        supports_vision=True,
        tags=("legacy", "vision"),
    ),
    ModelSpec(
        id="openai:gpt-4o-mini",
        provider="openai",
        model="gpt-4o-mini",
        display_name="GPT-4o mini",
        capability="chat",
        description="Previous-gen small model. Still cheap if you need 4o behavior.",
        context_window=128_000,
        max_output_tokens=16_000,
        input_price_per_1k=0.00015,
        output_price_per_1k=0.0006,
        tier="free",
        supports_streaming=True,
        supports_json_mode=True,
        supports_vision=True,
        tags=("legacy", "cheap", "fast"),
    ),
    # ── Anthropic (latest) ──────────────────────────────────────────────
    ModelSpec(
        id="anthropic:claude-opus-4-7",
        provider="anthropic",
        model="claude-opus-4-7",
        display_name="Claude Opus 4.7",
        capability="chat",
        description="Anthropic's peak flagship — a absolute powerhouse for long-running reasoning tasks and highly complex software planning.",
        context_window=1000000,
        max_output_tokens=100000,
        input_price_per_1k=0.015,
        output_price_per_1k=0.075,
        tier="team",
        supports_streaming=True,
        supports_vision=True,
        tags=("latest", "flagship", "premium", "writing", "reasoning"),
    ),
    ModelSpec(
        id="anthropic:claude-opus-4-6",
        provider="anthropic",
        model="claude-opus-4-6",
        display_name="Claude Opus 4.6",
        capability="chat",
        description="Anthropic's legacy flagship — best writing, reasoning, and brand voice.",
        context_window=200_000,
        max_output_tokens=64_000,
        input_price_per_1k=0.015,
        output_price_per_1k=0.075,
        tier="team",
        supports_streaming=True,
        supports_vision=True,
        tags=("legacy", "flagship", "premium", "writing", "reasoning"),
    ),
    ModelSpec(
        id="anthropic:claude-sonnet-4-5",
        provider="anthropic",
        model="claude-sonnet-4-5",
        display_name="Claude Sonnet 4.5",
        capability="chat",
        description="Balanced Claude — agentic tool use + long-form copy.",
        context_window=200_000,
        max_output_tokens=64_000,
        input_price_per_1k=0.003,
        output_price_per_1k=0.015,
        tier="pro",
        supports_streaming=True,
        supports_vision=True,
        tags=("latest", "balanced", "agents"),
    ),
    ModelSpec(
        id="anthropic:claude-haiku-4-5",
        provider="anthropic",
        model="claude-haiku-4-5",
        display_name="Claude Haiku 4.5",
        capability="chat",
        description="Fastest Claude — production volume copy, near-Sonnet quality.",
        context_window=200_000,
        max_output_tokens=64_000,
        input_price_per_1k=0.001,
        output_price_per_1k=0.005,
        tier="free",
        supports_streaming=True,
        supports_vision=True,
        tags=("latest", "cheap", "fast"),
    ),
    # ── Anthropic (legacy) ──────────────────────────────────────────────
    ModelSpec(
        id="anthropic:claude-3-5-sonnet",
        provider="anthropic",
        model="claude-3-5-sonnet-latest",
        display_name="Claude 3.5 Sonnet",
        capability="chat",
        description="Previous-gen Claude — still strong writing model.",
        context_window=200_000,
        max_output_tokens=8_000,
        input_price_per_1k=0.003,
        output_price_per_1k=0.015,
        tier="pro",
        supports_streaming=True,
        supports_vision=True,
        tags=("legacy", "writing"),
    ),
    ModelSpec(
        id="anthropic:claude-3-5-haiku",
        provider="anthropic",
        model="claude-3-5-haiku-latest",
        display_name="Claude 3.5 Haiku",
        capability="chat",
        description="Previous-gen small Claude. Cheap, fast.",
        context_window=200_000,
        max_output_tokens=8_000,
        input_price_per_1k=0.001,
        output_price_per_1k=0.005,
        tier="free",
        supports_streaming=True,
        tags=("legacy", "cheap"),
    ),
    # ── Gemini (latest) ─────────────────────────────────────────────────
    ModelSpec(
        id="gemini:gemini-3.5-pro",
        provider="gemini",
        model="gemini-3.5-pro",
        display_name="Gemini 3.5 Pro",
        capability="chat",
        description="Google DeepMind's flagship — exceptional reasoning and broad multi-modal capabilities across text, audio, and visual integrations with a 2M context window.",
        context_window=2000000,
        max_output_tokens=100000,
        input_price_per_1k=0.00125,
        output_price_per_1k=0.01,
        tier="pro",
        supports_vision=True,
        tags=("latest", "flagship", "long-context", "reasoning"),
    ),
    ModelSpec(
        id="gemini:gemini-2.5-pro",
        provider="gemini",
        model="gemini-2.5-pro",
        display_name="Gemini 2.5 Pro",
        capability="chat",
        description="Google's previous-gen flagship — reasoning-first, 2M context window.",
        context_window=2_000_000,
        max_output_tokens=64_000,
        input_price_per_1k=0.00125,
        output_price_per_1k=0.01,
        tier="pro",
        supports_vision=True,
        tags=("legacy", "flagship", "long-context", "reasoning"),
    ),
    ModelSpec(
        id="gemini:gemini-2.5-flash",
        provider="gemini",
        model="gemini-2.5-flash",
        display_name="Gemini 2.5 Flash",
        capability="chat",
        description="Cheapest top-tier model — huge context, blazing fast.",
        context_window=1_000_000,
        max_output_tokens=64_000,
        input_price_per_1k=0.0003,
        output_price_per_1k=0.0025,
        tier="free",
        supports_vision=True,
        tags=("latest", "cheap", "fast", "long-context"),
    ),
    # ── Gemini (legacy) ─────────────────────────────────────────────────
    ModelSpec(
        id="gemini:gemini-1.5-pro",
        provider="gemini",
        model="gemini-1.5-pro",
        display_name="Gemini 1.5 Pro",
        capability="chat",
        description="Previous-gen Google flagship with 2M context.",
        context_window=2_000_000,
        max_output_tokens=8_000,
        input_price_per_1k=0.00125,
        output_price_per_1k=0.005,
        tier="pro",
        supports_vision=True,
        tags=("legacy", "long-context"),
    ),
    ModelSpec(
        id="gemini:gemini-1.5-flash",
        provider="gemini",
        model="gemini-1.5-flash",
        display_name="Gemini 1.5 Flash",
        capability="chat",
        description="Previous-gen Flash. Cheap, very fast.",
        context_window=1_000_000,
        max_output_tokens=8_000,
        input_price_per_1k=0.000075,
        output_price_per_1k=0.0003,
        tier="free",
        tags=("legacy", "cheap", "fast"),
    ),
    # ── OpenRouter — unified gateway to 300+ models ────────────────────
    # Auto route — OpenRouter picks the best model for the prompt
    ModelSpec(
        id="openrouter:auto",
        provider="openrouter",
        model="openrouter/auto",
        display_name="Auto (OpenRouter)",
        capability="chat",
        description="OpenRouter picks the best model for your prompt.",
        context_window=128_000,
        input_price_per_1k=0.001,
        output_price_per_1k=0.004,
        tier="pro",
        supports_streaming=True,
        tags=("auto", "gateway"),
    ),
    # OpenAI models via OpenRouter
    ModelSpec(
        id="openrouter:gpt-5.5",
        provider="openrouter",
        model="openai/gpt-5.5",
        display_name="GPT-5.5 (OpenRouter)",
        capability="chat",
        description="OpenAI's top flagship GPT-5.5 via OpenRouter — no direct key needed, 1M context.",
        context_window=1000000,
        max_output_tokens=64000,
        input_price_per_1k=0.00125,
        output_price_per_1k=0.01,
        tier="pro",
        supports_streaming=True,
        supports_json_mode=True,
        supports_vision=True,
        tags=("openai", "latest", "flagship"),
    ),
    ModelSpec(
        id="openrouter:gpt-5",
        provider="openrouter",
        model="openai/gpt-5",
        display_name="GPT-5 (OpenRouter)",
        capability="chat",
        description="OpenAI GPT-5 via OpenRouter — legacy flagship, no OpenAI key needed.",
        context_window=400_000,
        max_output_tokens=32_000,
        input_price_per_1k=0.00125,
        output_price_per_1k=0.01,
        tier="pro",
        supports_streaming=True,
        supports_json_mode=True,
        supports_vision=True,
        tags=("openai", "legacy", "flagship"),
    ),
    ModelSpec(
        id="openrouter:gpt-5-mini",
        provider="openrouter",
        model="openai/gpt-5-mini",
        display_name="GPT-5 mini (OpenRouter)",
        capability="chat",
        description="OpenAI GPT-5 mini via OpenRouter — fast, cheap, no OpenAI key.",
        context_window=400_000,
        max_output_tokens=32_000,
        input_price_per_1k=0.00025,
        output_price_per_1k=0.002,
        tier="free",
        supports_streaming=True,
        supports_json_mode=True,
        supports_vision=True,
        tags=("openai", "latest", "cheap", "fast"),
    ),
    ModelSpec(
        id="openrouter:o4-mini",
        provider="openrouter",
        model="openai/o4-mini",
        display_name="o4 mini (OpenRouter)",
        capability="chat",
        description="OpenAI o4-mini via OpenRouter — reasoning-tuned, cheap chain-of-thought.",
        context_window=200_000,
        max_output_tokens=100_000,
        input_price_per_1k=0.0011,
        output_price_per_1k=0.0044,
        tier="free",
        supports_streaming=True,
        supports_json_mode=True,
        tags=("openai", "latest", "reasoning"),
    ),
    ModelSpec(
        id="openrouter:gpt-4o",
        provider="openrouter",
        model="openai/gpt-4o",
        display_name="GPT-4o (OpenRouter)",
        capability="chat",
        description="OpenAI GPT-4o via OpenRouter — vision, JSON mode, no API key needed.",
        context_window=128_000,
        max_output_tokens=16_000,
        input_price_per_1k=0.0025,
        output_price_per_1k=0.01,
        tier="pro",
        supports_streaming=True,
        supports_json_mode=True,
        supports_vision=True,
        tags=("openai", "vision"),
    ),
    ModelSpec(
        id="openrouter:gpt-4o-mini",
        provider="openrouter",
        model="openai/gpt-4o-mini",
        display_name="GPT-4o mini (OpenRouter)",
        capability="chat",
        description="Cheap OpenAI model via OpenRouter — no direct key needed.",
        context_window=128_000,
        max_output_tokens=16_000,
        input_price_per_1k=0.00015,
        output_price_per_1k=0.0006,
        tier="free",
        supports_streaming=True,
        supports_json_mode=True,
        supports_vision=True,
        tags=("openai", "cheap", "fast"),
    ),
    # Anthropic models via OpenRouter
    ModelSpec(
        id="openrouter:claude-opus-4-7",
        provider="openrouter",
        model="anthropic/claude-opus-4-7",
        display_name="Claude Opus 4.7 (OpenRouter)",
        capability="chat",
        description="Anthropic's peak flagship Claude Opus 4.7 via OpenRouter — absolute powerhouse for planning & orchestration.",
        context_window=1000000,
        max_output_tokens=100000,
        input_price_per_1k=0.015,
        output_price_per_1k=0.075,
        tier="team",
        supports_streaming=True,
        supports_vision=True,
        tags=("anthropic", "latest", "premium", "flagship"),
    ),
    ModelSpec(
        id="openrouter:claude-opus-4-6",
        provider="openrouter",
        model="anthropic/claude-opus-4-6",
        display_name="Claude Opus 4.6 (OpenRouter)",
        capability="chat",
        description="Anthropic's legacy flagship Claude 4.6 via OpenRouter — best-in-class writing & reasoning.",
        context_window=200_000,
        max_output_tokens=64_000,
        input_price_per_1k=0.015,
        output_price_per_1k=0.075,
        tier="team",
        supports_streaming=True,
        supports_vision=True,
        tags=("anthropic", "legacy", "flagship"),
    ),
    ModelSpec(
        id="openrouter:claude-sonnet-4-5",
        provider="openrouter",
        model="anthropic/claude-sonnet-4-5",
        display_name="Claude Sonnet 4.5 (OpenRouter)",
        capability="chat",
        description="Claude Sonnet 4.5 via OpenRouter — balanced agentic model.",
        context_window=200_000,
        max_output_tokens=64_000,
        input_price_per_1k=0.003,
        output_price_per_1k=0.015,
        tier="pro",
        supports_streaming=True,
        supports_vision=True,
        tags=("anthropic", "balanced", "agents"),
    ),
    ModelSpec(
        id="openrouter:claude-haiku-4-5",
        provider="openrouter",
        model="anthropic/claude-haiku-4-5",
        display_name="Claude Haiku 4.5 (OpenRouter)",
        capability="chat",
        description="Claude Haiku 4.5 via OpenRouter — fast, cheap, near-Sonnet quality.",
        context_window=200_000,
        max_output_tokens=64_000,
        input_price_per_1k=0.001,
        output_price_per_1k=0.005,
        tier="free",
        supports_streaming=True,
        supports_vision=True,
        tags=("anthropic", "fast", "cheap"),
    ),
    # Google models via OpenRouter
    ModelSpec(
        id="openrouter:gemini-3.5-pro",
        provider="openrouter",
        model="google/gemini-3.5-pro",
        display_name="Gemini 3.5 Pro (OpenRouter)",
        capability="chat",
        description="Google Gemini 3.5 Pro via OpenRouter — flagship reasoning + visual integration, 2M context.",
        context_window=2000000,
        max_output_tokens=100000,
        input_price_per_1k=0.00125,
        output_price_per_1k=0.01,
        tier="pro",
        supports_streaming=True,
        supports_vision=True,
        tags=("google", "latest", "long-context"),
    ),
    ModelSpec(
        id="openrouter:gemini-2.5-pro",
        provider="openrouter",
        model="google/gemini-2.5-pro-preview-05-06",
        display_name="Gemini 2.5 Pro (OpenRouter)",
        capability="chat",
        description="Google Gemini 2.5 Pro via OpenRouter — legacy flagship, 2M context.",
        context_window=2_000_000,
        max_output_tokens=64_000,
        input_price_per_1k=0.00125,
        output_price_per_1k=0.01,
        tier="pro",
        supports_streaming=True,
        supports_vision=True,
        tags=("google", "legacy", "long-context"),
    ),
    ModelSpec(
        id="openrouter:gemini-2.5-flash",
        provider="openrouter",
        model="google/gemini-2.5-flash-preview-05-06",
        display_name="Gemini 2.5 Flash (OpenRouter)",
        capability="chat",
        description="Gemini 2.5 Flash via OpenRouter — cheap, huge context, fast.",
        context_window=1_000_000,
        max_output_tokens=64_000,
        input_price_per_1k=0.0003,
        output_price_per_1k=0.0025,
        tier="free",
        supports_streaming=True,
        supports_vision=True,
        tags=("google", "fast", "cheap", "long-context"),
    ),
    # DeepSeek models via OpenRouter
    ModelSpec(
        id="openrouter:deepseek-v3",
        provider="openrouter",
        model="deepseek/deepseek-chat",
        display_name="DeepSeek V3 (OpenRouter)",
        capability="chat",
        description="DeepSeek V3 via OpenRouter — 1M context, strong reasoning.",
        context_window=1_000_000,
        max_output_tokens=8_000,
        input_price_per_1k=0.0005,
        output_price_per_1k=0.002,
        tier="free",
        supports_streaming=True,
        supports_json_mode=True,
        tags=("deepseek", "latest", "long-context"),
    ),
    ModelSpec(
        id="openrouter:deepseek-r1",
        provider="openrouter",
        model="deepseek/deepseek-r1",
        display_name="DeepSeek R1 (OpenRouter)",
        capability="chat",
        description="DeepSeek R1 via OpenRouter — chain-of-thought reasoning.",
        context_window=128_000,
        max_output_tokens=8_000,
        input_price_per_1k=0.001,
        output_price_per_1k=0.004,
        tier="pro",
        supports_streaming=True,
        tags=("deepseek", "latest", "reasoning"),
    ),
    # Mistral via OpenRouter
    ModelSpec(
        id="openrouter:mistral-large-3",
        provider="openrouter",
        model="mistralai/mistral-large-2411",
        display_name="Mistral Large 3 (OpenRouter)",
        capability="chat",
        description="Mistral Large 3 via OpenRouter — flagship European open-weight model with top-tier agentic and multilingual skills.",
        context_window=128_000,
        max_output_tokens=32_000,
        input_price_per_1k=0.003,
        output_price_per_1k=0.009,
        tier="pro",
        supports_streaming=True,
        supports_json_mode=True,
        tags=("mistral", "latest", "flagship"),
    ),
    # Meta Llama models via OpenRouter
    ModelSpec(
        id="openrouter:llama-4-maverick",
        provider="openrouter",
        model="meta-llama/llama-4-maverick",
        display_name="Llama 4 Maverick (OpenRouter)",
        capability="chat",
        description="Meta's latest open-weight flagship — strong reasoning + vision.",
        context_window=1_000_000,
        input_price_per_1k=0.0002,
        output_price_per_1k=0.0002,
        tier="free",
        supports_streaming=True,
        supports_vision=True,
        tags=("meta", "latest", "open"),
    ),
    ModelSpec(
        id="openrouter:llama-4-scout",
        provider="openrouter",
        model="meta-llama/llama-4-scout",
        display_name="Llama 4 Scout (OpenRouter)",
        capability="chat",
        description="Smaller Llama 4 via OpenRouter — fast, cheap, 10M context.",
        context_window=10_000_000,
        input_price_per_1k=0.00005,
        output_price_per_1k=0.00005,
        tier="free",
        supports_streaming=True,
        supports_vision=True,
        tags=("meta", "latest", "cheap", "long-context"),
    ),
    ModelSpec(
        id="openrouter:llama-3.3-70b",
        provider="openrouter",
        model="meta-llama/llama-3.3-70b-instruct",
        display_name="Llama 3.3 70B (OpenRouter)",
        capability="chat",
        description="Meta Llama 3.3 70B via OpenRouter — proven open model.",
        context_window=128_000,
        input_price_per_1k=0.0001,
        output_price_per_1k=0.0001,
        tier="free",
        supports_streaming=True,
        tags=("meta", "open"),
    ),
    # Qwen via OpenRouter
    ModelSpec(
        id="openrouter:qwen-3.7-max",
        provider="openrouter",
        model="qwen/qwen-3.7-max",
        display_name="Qwen 3.7 Max (OpenRouter)",
        capability="chat",
        description="Alibaba's flagship Qwen 3.7 Max via OpenRouter — Chinese open-weights leader that matches Western high-tier models.",
        context_window=128000,
        input_price_per_1k=0.0024,
        output_price_per_1k=0.0096,
        tier="pro",
        supports_streaming=True,
        supports_json_mode=True,
        tags=("alibaba", "latest", "flagship"),
    ),
    ModelSpec(
        id="openrouter:qwen-2.5-72b",
        provider="openrouter",
        model="qwen/qwen-2.5-72b-instruct",
        display_name="Qwen 2.5 72B (OpenRouter)",
        capability="chat",
        description="Alibaba's legacy top open model — strong across the board.",
        context_window=128_000,
        input_price_per_1k=0.00045,
        output_price_per_1k=0.00065,
        tier="free",
        supports_streaming=True,
        tags=("alibaba", "legacy", "open"),
    ),
    ModelSpec(
        id="openrouter:qwen-2.5-coder-32b",
        provider="openrouter",
        model="qwen/qwen-2.5-coder-32b-instruct",
        display_name="Qwen 2.5 Coder 32B (OpenRouter)",
        capability="chat",
        description="Specialized code generation model via OpenRouter.",
        context_window=128_000,
        input_price_per_1k=0.0003,
        output_price_per_1k=0.0003,
        tier="free",
        supports_streaming=True,
        tags=("alibaba", "code", "latest"),
    ),
    # Chinese models via OpenRouter
    ModelSpec(
        id="openrouter:qwen3-235b",
        provider="openrouter",
        model="alibaba/qwen3-235b-a12b",
        display_name="Qwen3 235B (OpenRouter)",
        capability="chat",
        description="Alibaba Qwen3 235B MoE via OpenRouter — flagship Chinese reasoning model.",
        context_window=131_072,
        max_output_tokens=32_000,
        input_price_per_1k=0.005,
        output_price_per_1k=0.02,
        tier="team",
        supports_streaming=True,
        supports_vision=True,
        tags=("chinese", "alibaba", "flagship", "moe"),
    ),
    ModelSpec(
        id="openrouter:glm-4",
        provider="openrouter",
        model="zhipu/glm-4",
        display_name="GLM-4 (OpenRouter)",
        capability="chat",
        description="Zhipu AI GLM-4 via OpenRouter — strong Chinese language model.",
        context_window=128_000,
        max_output_tokens=8_000,
        input_price_per_1k=0.001,
        output_price_per_1k=0.001,
        tier="free",
        supports_streaming=True,
        tags=("chinese", "zhipu", "latest"),
    ),
    ModelSpec(
        id="openrouter:yi-lightning",
        provider="openrouter",
        model="01-ai/yi-lightning",
        display_name="Yi Lightning (OpenRouter)",
        capability="chat",
        description="01.AI Yi Lightning via OpenRouter — fast, cheap Chinese model.",
        context_window=128_000,
        max_output_tokens=8_000,
        input_price_per_1k=0.0001,
        output_price_per_1k=0.0001,
        tier="free",
        supports_streaming=True,
        tags=("chinese", "01-ai", "fast", "cheap"),
    ),
    ModelSpec(
        id="openrouter:baichuan-4",
        provider="openrouter",
        model="baichuan/baichuan-4",
        display_name="Baichuan 4 (OpenRouter)",
        capability="chat",
        description="Baichuan Intelligent's latest model via OpenRouter.",
        context_window=128_000,
        input_price_per_1k=0.001,
        output_price_per_1k=0.001,
        tier="free",
        supports_streaming=True,
        tags=("chinese", "baichuan", "latest"),
    ),
    ModelSpec(
        id="openrouter:minimax-m1",
        provider="openrouter",
        model="minimax/minimax-m1",
        display_name="MiniMax M1 (OpenRouter)",
        capability="chat",
        description="MiniMax M1 via OpenRouter — strong Chinese MoE model.",
        context_window=128_000,
        max_output_tokens=8_000,
        input_price_per_1k=0.0005,
        output_price_per_1k=0.0005,
        tier="free",
        supports_streaming=True,
        tags=("chinese", "minimax", "latest"),
    ),
    ModelSpec(
        id="openrouter:deepseek-v3-0324",
        provider="openrouter",
        model="deepseek/deepseek-chat-v3-0324",
        display_name="DeepSeek V3-0324 (OpenRouter)",
        capability="chat",
        description="DeepSeek V3 latest version via OpenRouter — 1M context, improved reasoning.",
        context_window=1_000_000,
        max_output_tokens=8_000,
        input_price_per_1k=0.0005,
        output_price_per_1k=0.002,
        tier="free",
        supports_streaming=True,
        supports_json_mode=True,
        tags=("chinese", "deepseek", "latest", "long-context"),
    ),
    ModelSpec(
        id="openrouter:step-2",
        provider="openrouter",
        model="stepfun/step-2",
        display_name="Step-2 (OpenRouter)",
        capability="chat",
        description="StepFun Step-2 via OpenRouter — 16K context, Chinese MoE model.",
        context_window=16_000,
        input_price_per_1k=0.0005,
        output_price_per_1k=0.0005,
        tier="free",
        supports_streaming=True,
        tags=("chinese", "stepfun", "latest"),
    ),
    # ── DeepSeek ─────────────────────────────────────────────────────────
    ModelSpec(
        id="deepseek:chat",
        provider="deepseek",
        model="deepseek-chat",
        display_name="DeepSeek Chat V3",
        capability="chat",
        description="DeepSeek's latest general-purpose model — strong reasoning, 1M context.",
        context_window=1_000_000,
        max_output_tokens=8_000,
        input_price_per_1k=0.0005,
        output_price_per_1k=0.002,
        tier="free",
        supports_streaming=True,
        supports_json_mode=True,
        requires_setting="deepseek_api_key",
        tags=("latest", "reasoning", "long-context"),
    ),
    ModelSpec(
        id="deepseek:reasoner",
        provider="deepseek",
        model="deepseek-reasoner",
        display_name="DeepSeek R1",
        capability="chat",
        description="DeepSeek R1 — chain-of-thought reasoning model, excels at math and logic.",
        context_window=128_000,
        max_output_tokens=8_000,
        input_price_per_1k=0.001,
        output_price_per_1k=0.004,
        tier="pro",
        supports_streaming=True,
        requires_setting="deepseek_api_key",
        tags=("latest", "reasoning", "deep-think"),
    ),
    # ── Groq ──────────────────────────────────────────────────────────────
    ModelSpec(
        id="groq:llama-4-maverick",
        provider="groq",
        model="meta-llama/llama-4-maverick",
        display_name="Llama 4 Maverick (Groq)",
        capability="chat",
        description="Llama 4 Maverick via Groq — blazing fast inference.",
        context_window=128_000,
        input_price_per_1k=0.0001,
        output_price_per_1k=0.0001,
        tier="free",
        supports_streaming=True,
        requires_setting="groq_api_key",
        tags=("fast", "open", "latest"),
    ),
    ModelSpec(
        id="groq:mixtral-8x7b",
        provider="groq",
        model="mixtral-8x7b-32768",
        display_name="Mixtral 8x7B (Groq)",
        capability="chat",
        description="Mixtral MoE via Groq — fast, multilingual, 32K context.",
        context_window=32_768,
        input_price_per_1k=0.00005,
        output_price_per_1k=0.00005,
        tier="free",
        supports_streaming=True,
        requires_setting="groq_api_key",
        tags=("fast", "cheap", "open"),
    ),
    ModelSpec(
        id="groq:llama-3.3-70b",
        provider="groq",
        model="meta-llama/llama-3.3-70b-versatile",
        display_name="Llama 3.3 70B (Groq)",
        capability="chat",
        description="Meta Llama 3.3 70B via Groq — top-tier open model, blazing inference.",
        context_window=128_000,
        input_price_per_1k=0.0001,
        output_price_per_1k=0.0001,
        tier="free",
        supports_streaming=True,
        requires_setting="groq_api_key",
        tags=("fast", "open", "latest", "flagship"),
    ),
    ModelSpec(
        id="groq:deepseek-r1",
        provider="groq",
        model="deepseek-r1-distill-llama-70b",
        display_name="DeepSeek R1 Distill 70B (Groq)",
        capability="chat",
        description="DeepSeek R1 reasoning via Groq — fast chain-of-thought.",
        context_window=128_000,
        input_price_per_1k=0.0002,
        output_price_per_1k=0.0002,
        tier="free",
        supports_streaming=True,
        requires_setting="groq_api_key",
        tags=("fast", "reasoning", "latest"),
    ),
    ModelSpec(
        id="groq:qwen-2.5-32b",
        provider="groq",
        model="qwen-2.5-32b",
        display_name="Qwen 2.5 32B (Groq)",
        capability="chat",
        description="Alibaba Qwen 2.5 32B via Groq — strong multilingual, 128K context.",
        context_window=128_000,
        input_price_per_1k=0.0001,
        output_price_per_1k=0.0001,
        tier="free",
        supports_streaming=True,
        requires_setting="groq_api_key",
        tags=("fast", "cheap", "multilingual"),
    ),
    # ── Mistral ──────────────────────────────────────────────────────────
    ModelSpec(
        id="mistral:large",
        provider="mistral",
        model="mistral-large-latest",
        display_name="Mistral Large",
        capability="chat",
        description="Mistral's flagship — strong reasoning, multilingual, function calling.",
        context_window=128_000,
        max_output_tokens=32_000,
        input_price_per_1k=0.003,
        output_price_per_1k=0.009,
        tier="pro",
        supports_streaming=True,
        supports_json_mode=True,
        requires_setting="mistral_api_key",
        tags=("latest", "flagship", "multilingual"),
    ),
    ModelSpec(
        id="mistral:small",
        provider="mistral",
        model="mistral-small-latest",
        display_name="Mistral Small",
        capability="chat",
        description="Fast Mistral model — great latency, solid quality.",
        context_window=32_000,
        max_output_tokens=8_000,
        input_price_per_1k=0.001,
        output_price_per_1k=0.003,
        tier="free",
        supports_streaming=True,
        requires_setting="mistral_api_key",
        tags=("fast", "cheap"),
    ),
    # ── DashScope (Alibaba Qwen — direct, OpenAI-compatible) ────────────
    ModelSpec(
        id="dashscope:qwen-max",
        provider="dashscope",
        model="qwen-max",
        display_name="Qwen Max",
        capability="chat",
        description="Alibaba's strongest Qwen model — top reasoning, 32K output.",
        context_window=131_072,
        max_output_tokens=32_000,
        input_price_per_1k=0.0024,
        output_price_per_1k=0.0096,
        tier="pro",
        supports_streaming=True,
        supports_json_mode=True,
        requires_setting="dashscope_api_key",
        tags=("chinese", "flagship", "latest"),
    ),
    ModelSpec(
        id="dashscope:qwen-plus",
        provider="dashscope",
        model="qwen-plus",
        display_name="Qwen Plus",
        capability="chat",
        description="Alibaba Qwen Plus — balanced quality/speed, multilingual.",
        context_window=131_072,
        max_output_tokens=8_000,
        input_price_per_1k=0.0008,
        output_price_per_1k=0.002,
        tier="free",
        supports_streaming=True,
        supports_json_mode=True,
        is_default=True,
        requires_setting="dashscope_api_key",
        tags=("chinese", "balanced", "multilingual"),
    ),
    ModelSpec(
        id="dashscope:qwen-turbo",
        provider="dashscope",
        model="qwen-turbo",
        display_name="Qwen Turbo",
        capability="chat",
        description="Alibaba Qwen Turbo — fastest Qwen, cheap, 1M context.",
        context_window=1_000_000,
        max_output_tokens=8_000,
        input_price_per_1k=0.0003,
        output_price_per_1k=0.0006,
        tier="free",
        supports_streaming=True,
        supports_json_mode=True,
        requires_setting="dashscope_api_key",
        tags=("chinese", "fast", "cheap", "long-context"),
    ),
    ModelSpec(
        id="dashscope:qwen3-235b",
        provider="dashscope",
        model="qwen3-235b-a12b",
        display_name="Qwen3 235B",
        capability="chat",
        description="Alibaba Qwen3 235B MoE — flagship reasoning, 32K output, think mode.",
        context_window=131_072,
        max_output_tokens=32_000,
        input_price_per_1k=0.005,
        output_price_per_1k=0.02,
        tier="team",
        supports_streaming=True,
        supports_vision=True,
        requires_setting="dashscope_api_key",
        tags=("chinese", "flagship", "reasoning", "moe"),
    ),
]


# ---------------------------------------------------------------------------
# Image models
# ---------------------------------------------------------------------------
_IMAGE_MODELS: list[ModelSpec] = [
    ModelSpec(
        id="image:gpt-image-2",
        provider="openai",
        model="gpt-image-2",
        display_name="GPT-Image-2.0",
        capability="image",
        description="OpenAI's latest flagship image synthesis model with agentic planning, multi-step complex edits, and pixel-perfect typography.",
        price_per_image=0.04,
        tier="pro",
        is_default=True,
        tags=("flagship", "text-in-image", "agentic-reasoning"),
    ),
    ModelSpec(
        id="image:grok-imagine",
        provider="replicate",
        model="xai/grok-imagine",
        display_name="Grok Imagine",
        capability="image",
        description="xAI's flagship creative design engine powered by the Aurora engine, offering superior spatial intelligence, exact layout text, and native aspect ratios.",
        price_per_image=0.04,
        tier="pro",
        tags=("flagship", "text-in-image", "aurora-engine"),
    ),
    ModelSpec(
        id="image:gpt-image-1",
        provider="openai",
        model="gpt-image-1",
        display_name="GPT-Image-1",
        capability="image",
        description="OpenAI's legacy image model — best text rendering and prompt adherence.",
        price_per_image=0.04,
        tier="pro",
        tags=("legacy", "text-in-image"),
    ),
    ModelSpec(
        id="image:flux-1.1-pro",
        provider="replicate",
        model="black-forest-labs/flux-1.1-pro",
        display_name="Flux 1.1 Pro",
        capability="image",
        description="Black Forest Labs Flux Pro via Replicate. Photo-real and stylized.",
        price_per_image=0.04,
        tier="pro",
        tags=("photo", "stylized"),
    ),
    ModelSpec(
        id="image:flux-schnell",
        provider="replicate",
        model="black-forest-labs/flux-schnell",
        display_name="Flux Schnell",
        capability="image",
        description="Fast variant — great for iterating on concepts.",
        price_per_image=0.003,
        tier="free",
        tags=("fast", "cheap"),
    ),
    ModelSpec(
        id="image:sdxl",
        provider="replicate",
        model="stability-ai/sdxl:7762fd07cf82c948538e41f63f77d685e02b063e37e496e96eefd46c929f9bdc",
        display_name="Stable Diffusion XL",
        capability="image",
        description="Stability SDXL — versatile open-weights model.",
        price_per_image=0.0035,
        tier="free",
        tags=("open-weights",),
    ),
]


# ---------------------------------------------------------------------------
# Video models
# ---------------------------------------------------------------------------
_VIDEO_MODELS: list[ModelSpec] = [
    ModelSpec(
        id="video:runway-gen3",
        provider="runway",
        model="gen3a_turbo",
        display_name="Runway Gen-3 Alpha Turbo",
        capability="video",
        description="Runway Gen-3 Turbo — cinematic 5–10s clips.",
        price_per_second=0.05,
        tier="team",
        tags=("cinematic",),
    ),
    ModelSpec(
        id="video:veo-3",
        provider="veo",
        model="veo-3.0-generate-preview",
        display_name="Google Veo 3",
        capability="video",
        description="Google's Veo 3 — high-fidelity short clips, native audio.",
        price_per_second=0.075,
        tier="team",
        is_default=True,
        tags=("flagship", "audio"),
    ),
]


MODEL_CATALOG: dict[str, ModelSpec] = {
    spec.id: spec
    for spec in (*_CHAT_MODELS, *_IMAGE_MODELS, *_VIDEO_MODELS)
}


# ---------------------------------------------------------------------------
# Lookup helpers
# ---------------------------------------------------------------------------
def get_model(model_id: str) -> ModelSpec | None:
    return MODEL_CATALOG.get(model_id)


def _is_available(spec: ModelSpec) -> bool:
    """A model is available iff the server has the provider key configured."""
    attr = spec.settings_attr
    if not attr:
        return True
    settings = get_settings()
    return bool(getattr(settings, attr, ""))


def available_models(capability: Capability | None = None) -> list[ModelSpec]:
    specs = list(MODEL_CATALOG.values())
    if capability:
        specs = [s for s in specs if s.capability == capability]
    return [s for s in specs if _is_available(s)]


def list_chat_models(available_only: bool = True) -> list[ModelSpec]:
    return _maybe_filter(_CHAT_MODELS, available_only)


def list_image_models(available_only: bool = True) -> list[ModelSpec]:
    return _maybe_filter(_IMAGE_MODELS, available_only)


def list_video_models(available_only: bool = True) -> list[ModelSpec]:
    return _maybe_filter(_VIDEO_MODELS, available_only)


def _maybe_filter(specs: list[ModelSpec], available_only: bool) -> list[ModelSpec]:
    if not available_only:
        return list(specs)
    return [s for s in specs if _is_available(s)]


def default_model(capability: Capability) -> ModelSpec | None:
    """Pick the user-facing default for a capability.

    Preference order:
      1. A model marked `is_default=True` whose key is configured
      2. The first available model in that capability
      3. The first model in the catalog (even if key missing) — caller decides
    """
    pool = [s for s in MODEL_CATALOG.values() if s.capability == capability]
    available = [s for s in pool if _is_available(s)]
    for s in available:
        if s.is_default:
            return s
    if available:
        return available[0]
    for s in pool:
        if s.is_default:
            return s
    return pool[0] if pool else None
