"""Integration provider catalog.

Supports two auth kinds:
- `oauth2`: standard authorization-code flow with the existing oauth_flow helpers.
- `token`:  user-pasted secret (e.g. Telegram bot token, restaurant POS API key).

Providers carry a `category` so the integrations UI can group them.
Providers without env-side client credentials still appear in the catalog
(so users can see what's available) but `configured=False` blocks Connect.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class OAuthProvider:
    key: str
    display_name: str
    authorize_url: str = ""
    token_url: str = ""
    scopes: list[str] = field(default_factory=list)
    scope_separator: str = " "
    auth_kind: str = "oauth2"  # oauth2 | token
    extra_authorize_params: dict[str, str] = field(default_factory=dict)
    extra_token_params: dict[str, str] = field(default_factory=dict)
    uses_basic_auth_for_token: bool = False
    token_body_format: str = "form"  # form | json
    revoke_url: str | None = None
    # New fields
    category: str = "productivity"
    icon: str = ""  # emoji or short tag (frontend uses fallback when empty)
    description: str = ""
    token_label: str = "API Token"  # for auth_kind=token UI
    token_help_url: str = ""
    coming_soon: bool = False  # show in catalog, disable connect


# ──────────────────────────────────────────────────────────────────────────
# OAuth2 providers — fully wired through helix.integrations.oauth_flow
# ──────────────────────────────────────────────────────────────────────────

_OAUTH: dict[str, OAuthProvider] = {
    "canva": OAuthProvider(
        key="canva",
        display_name="Canva",
        category="design",
        icon="🎨",
        description="Design boards, brand kits, and asset library.",
        authorize_url="https://www.canva.com/api/oauth/authorize",
        token_url="https://api.canva.com/rest/v1/oauth/token",
        scopes=["design:content:read", "design:content:write", "asset:read", "asset:write"],
        uses_basic_auth_for_token=True,
        extra_authorize_params={"response_type": "code"},
    ),
    "figma": OAuthProvider(
        key="figma",
        display_name="Figma",
        category="design",
        icon="✏️",
        description="Read frames and component libraries for design hand-off.",
        authorize_url="https://www.figma.com/oauth",
        token_url="https://www.figma.com/api/oauth/token",
        scopes=["file_read"],
        scope_separator=",",
        extra_authorize_params={"response_type": "code"},
    ),
    "notion": OAuthProvider(
        key="notion",
        display_name="Notion",
        category="productivity",
        icon="📓",
        description="Publish briefs and creative wikis to Notion.",
        authorize_url="https://api.notion.com/v1/oauth/authorize",
        token_url="https://api.notion.com/v1/oauth/token",
        scopes=[],
        uses_basic_auth_for_token=True,
        token_body_format="json",
        extra_authorize_params={"response_type": "code", "owner": "user"},
    ),
    "google": OAuthProvider(
        key="google",
        display_name="Gmail (Google)",
        category="productivity",
        icon="✉️",
        description="Draft campaign emails directly in Gmail.",
        authorize_url="https://accounts.google.com/o/oauth2/v2/auth",
        token_url="https://oauth2.googleapis.com/token",
        scopes=[
            "https://www.googleapis.com/auth/gmail.compose",
            "https://www.googleapis.com/auth/userinfo.email",
            "openid",
        ],
        extra_authorize_params={
            "response_type": "code",
            "access_type": "offline",
            "prompt": "consent",
        },
        revoke_url="https://oauth2.googleapis.com/revoke",
    ),
}


# ──────────────────────────────────────────────────────────────────────────
# Token providers — user pastes an API key/secret/token
# ──────────────────────────────────────────────────────────────────────────

_TOKEN: dict[str, OAuthProvider] = {
    # Messaging
    "telegram": OAuthProvider(
        key="telegram",
        display_name="Telegram",
        category="messaging",
        icon="✈️",
        description="Chat with Helix from any Telegram client via your own bot.",
        auth_kind="token",
        token_label="Bot Token",
        token_help_url="https://core.telegram.org/bots#how-do-i-create-a-bot",
    ),
    "slack": OAuthProvider(
        key="slack",
        display_name="Slack",
        category="messaging",
        icon="💬",
        description="Post run updates and pull conversations from Slack.",
        auth_kind="token",
        token_label="Bot User OAuth Token (xoxb-…)",
        token_help_url="https://api.slack.com/apps",
    ),
    "discord": OAuthProvider(
        key="discord",
        display_name="Discord",
        category="messaging",
        icon="🎮",
        description="Bot integration for community channels.",
        auth_kind="token",
        token_label="Bot Token",
        token_help_url="https://discord.com/developers/applications",
    ),
    "whatsapp_business": OAuthProvider(
        key="whatsapp_business",
        display_name="WhatsApp Business",
        category="messaging",
        icon="📱",
        description="Send marketing + customer messages via Meta Cloud API.",
        auth_kind="token",
        token_label="Permanent Access Token",
        token_help_url="https://developers.facebook.com/docs/whatsapp/cloud-api/get-started",
    ),
    # Meta family
    "meta_pages": OAuthProvider(
        key="meta_pages",
        display_name="Facebook Pages",
        category="meta",
        icon="📘",
        description="Schedule posts, read insights, run page replies.",
        auth_kind="token",
        token_label="Page Access Token",
        token_help_url="https://developers.facebook.com/tools/explorer/",
    ),
    "instagram_business": OAuthProvider(
        key="instagram_business",
        display_name="Instagram Business",
        category="meta",
        icon="📷",
        description="Publish to feed/Reels, read DM + insights via Graph API.",
        auth_kind="token",
        token_label="IG User Access Token",
        token_help_url="https://developers.facebook.com/docs/instagram-api",
    ),
    "meta_ads": OAuthProvider(
        key="meta_ads",
        display_name="Meta Ads",
        category="meta",
        icon="📊",
        description="Create + report Facebook/Instagram ad campaigns.",
        auth_kind="token",
        token_label="Marketing API Token",
        token_help_url="https://developers.facebook.com/docs/marketing-apis",
    ),
    "threads": OAuthProvider(
        key="threads",
        display_name="Threads",
        category="meta",
        icon="🧵",
        description="Cross-post to Threads via Meta API.",
        auth_kind="token",
        token_label="Threads Access Token",
        token_help_url="https://developers.facebook.com/docs/threads",
    ),
    # Restaurant / POS
    "toast": OAuthProvider(
        key="toast",
        display_name="Toast POS",
        category="restaurant",
        icon="🍞",
        description="Menu sync, order history, loyalty data.",
        auth_kind="token",
        token_label="API Client Secret",
        token_help_url="https://doc.toasttab.com/openapi/",
    ),
    "square": OAuthProvider(
        key="square",
        display_name="Square",
        category="restaurant",
        icon="◼️",
        description="Items, payments, inventory, loyalty.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://developer.squareup.com/apps",
    ),
    "resy": OAuthProvider(
        key="resy",
        display_name="Resy",
        category="restaurant",
        icon="🍽️",
        description="Reservations, covers, guest history.",
        auth_kind="token",
        token_label="API Key",
        token_help_url="https://resy.com/api-documentation",
    ),
    "opentable": OAuthProvider(
        key="opentable",
        display_name="OpenTable",
        category="restaurant",
        icon="📖",
        description="Reservations + diner profiles.",
        auth_kind="token",
        token_label="Partner Token",
        token_help_url="https://www.opentable.com/booking/api",
    ),
    "doordash": OAuthProvider(
        key="doordash",
        display_name="DoorDash Drive",
        category="restaurant",
        icon="🛵",
        description="Delivery orchestration + menu sync.",
        auth_kind="token",
        token_label="JWT Signing Secret",
        token_help_url="https://developer.doordash.com/",
    ),
    "ubereats": OAuthProvider(
        key="ubereats",
        display_name="Uber Eats",
        category="restaurant",
        icon="🥡",
        description="Store, menu, and order webhooks.",
        auth_kind="token",
        token_label="OAuth Access Token",
        token_help_url="https://developer.uber.com/docs/eats",
    ),
    "yelp": OAuthProvider(
        key="yelp",
        display_name="Yelp Fusion",
        category="restaurant",
        icon="⭐",
        description="Reviews + business profile management.",
        auth_kind="token",
        token_label="Fusion API Key",
        token_help_url="https://www.yelp.com/developers",
    ),
    "google_business": OAuthProvider(
        key="google_business",
        display_name="Google Business Profile",
        category="restaurant",
        icon="📍",
        description="Posts, reviews, photos for Google Maps presence.",
        auth_kind="token",
        token_label="OAuth Access Token",
        token_help_url="https://developers.google.com/my-business",
    ),
    # E-commerce
    "shopify": OAuthProvider(
        key="shopify",
        display_name="Shopify",
        category="ecommerce",
        icon="🛍️",
        description="Storefront, products, orders, abandoned-cart.",
        auth_kind="token",
        token_label="Admin API Access Token",
        token_help_url="https://shopify.dev/docs/api/admin",
    ),
    "stripe": OAuthProvider(
        key="stripe",
        display_name="Stripe",
        category="ecommerce",
        icon="💳",
        description="Payments, invoices, billing automation.",
        auth_kind="token",
        token_label="Secret API Key (sk_…)",
        token_help_url="https://dashboard.stripe.com/apikeys",
    ),
    "twilio": OAuthProvider(
        key="twilio",
        display_name="Twilio",
        category="messaging",
        icon="☎️",
        description="SMS, WhatsApp, and voice messaging API.",
        auth_kind="token",
        token_label="Account SID + Auth Token",
        token_help_url="https://console.twilio.com/",
    ),
    "woocommerce": OAuthProvider(
        key="woocommerce",
        display_name="WooCommerce",
        category="ecommerce",
        icon="🛒",
        description="WordPress-based store + REST API.",
        auth_kind="token",
        token_label="Consumer Key:Secret",
        token_help_url="https://woocommerce.com/document/rest-api/",
    ),
    # Marketing
    "mailchimp": OAuthProvider(
        key="mailchimp",
        display_name="Mailchimp",
        category="marketing",
        icon="📬",
        description="Email lists, automations, journeys.",
        auth_kind="token",
        token_label="API Key",
        token_help_url="https://us1.admin.mailchimp.com/account/api/",
    ),
    "klaviyo": OAuthProvider(
        key="klaviyo",
        display_name="Klaviyo",
        category="marketing",
        icon="📈",
        description="E-commerce CRM, segmentation, flows.",
        auth_kind="token",
        token_label="Private API Key",
        token_help_url="https://www.klaviyo.com/account#api-keys-tab",
    ),
    "hubspot": OAuthProvider(
        key="hubspot",
        display_name="HubSpot",
        category="marketing",
        icon="🧲",
        description="CRM contacts, deals, marketing.",
        auth_kind="token",
        token_label="Private App Token",
        token_help_url="https://developers.hubspot.com/docs/api/private-apps",
    ),
    "sendgrid": OAuthProvider(
        key="sendgrid",
        display_name="SendGrid",
        category="marketing",
        icon="🛫",
        description="Transactional + bulk email API.",
        auth_kind="token",
        token_label="API Key (SG.…)",
        token_help_url="https://app.sendgrid.com/settings/api_keys",
    ),
    # Social
    "linkedin": OAuthProvider(
        key="linkedin",
        display_name="LinkedIn",
        category="social",
        icon="💼",
        description="Company page posts + ad campaigns.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://developer.linkedin.com/",
    ),
    "twitter": OAuthProvider(
        key="twitter",
        display_name="X / Twitter",
        category="social",
        icon="✖️",
        description="Tweet drafts, threads, listening.",
        auth_kind="token",
        token_label="Bearer Token",
        token_help_url="https://developer.twitter.com/",
    ),
    "tiktok_business": OAuthProvider(
        key="tiktok_business",
        display_name="TikTok Business",
        category="social",
        icon="🎵",
        description="Creator content + Spark Ads campaigns.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://business-api.tiktok.com/",
    ),
    "youtube": OAuthProvider(
        key="youtube",
        display_name="YouTube",
        category="social",
        icon="▶️",
        description="Upload videos, manage channel, comments.",
        auth_kind="token",
        token_label="OAuth Access Token",
        token_help_url="https://developers.google.com/youtube/registering_an_application",
    ),
    "pinterest": OAuthProvider(
        key="pinterest",
        display_name="Pinterest",
        category="social",
        icon="📌",
        description="Pin scheduling and analytics.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://developers.pinterest.com/docs/getting-started/authentication/",
    ),
    # Productivity / project
    "airtable": OAuthProvider(
        key="airtable",
        display_name="Airtable",
        category="productivity",
        icon="🗂️",
        description="Operational bases for content + campaigns.",
        auth_kind="token",
        token_label="Personal Access Token",
        token_help_url="https://airtable.com/create/tokens",
    ),
    "linear": OAuthProvider(
        key="linear",
        display_name="Linear",
        category="productivity",
        icon="📐",
        description="Issues + cycles for product/eng tasks.",
        auth_kind="token",
        token_label="Personal API Key",
        token_help_url="https://linear.app/settings/api",
    ),
    "asana": OAuthProvider(
        key="asana",
        display_name="Asana",
        category="productivity",
        icon="🧷",
        description="Tasks + projects + timelines.",
        auth_kind="token",
        token_label="Personal Access Token",
        token_help_url="https://app.asana.com/0/my-apps",
    ),
    "calendly": OAuthProvider(
        key="calendly",
        display_name="Calendly",
        category="productivity",
        icon="🗓️",
        description="Booking links + event types.",
        auth_kind="token",
        token_label="Personal Access Token",
        token_help_url="https://calendly.com/integrations/api_webhooks",
    ),
    # Analytics
    "posthog": OAuthProvider(
        key="posthog",
        display_name="PostHog",
        category="analytics",
        icon="📊",
        description="Product analytics + experiments.",
        auth_kind="token",
        token_label="Personal API Key",
        token_help_url="https://app.posthog.com/settings/user-api-keys",
    ),
    "mixpanel": OAuthProvider(
        key="mixpanel",
        display_name="Mixpanel",
        category="analytics",
        icon="📉",
        description="Funnels, retention, cohorts.",
        auth_kind="token",
        token_label="Service Account Secret",
        token_help_url="https://developer.mixpanel.com/reference/service-accounts",
    ),
    "ga4": OAuthProvider(
        key="ga4",
        display_name="Google Analytics 4",
        category="analytics",
        icon="📈",
        description="Web + app traffic insights.",
        auth_kind="token",
        token_label="OAuth Access Token",
        token_help_url="https://developers.google.com/analytics/devguides/reporting/data/v1",
    ),
    # CRM & Support
    "salesforce": OAuthProvider(
        key="salesforce",
        display_name="Salesforce",
        category="crm",
        icon="☁️",
        description="CRM leads, opportunities, and pipeline management.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://help.salesforce.com/s/articleView?id=sf.user_security_token.htm",
    ),
    "zendesk": OAuthProvider(
        key="zendesk",
        display_name="Zendesk",
        category="support",
        icon="🎧",
        description="Support tickets, agents, and customer service.",
        auth_kind="token",
        token_label="API Token",
        token_help_url="https://support.zendesk.com/hc/en-us/articles/4408889192858",
    ),
    "intercom": OAuthProvider(
        key="intercom",
        display_name="Intercom",
        category="support",
        icon="💬",
        description="Conversations, messages, and user management.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://developers.intercom.com/docs/build-an-integration/learn-more/authentication",
    ),
    "jira": OAuthProvider(
        key="jira",
        display_name="Jira",
        category="productivity",
        icon="📋",
        description="Issue tracking, sprints, and project management.",
        auth_kind="token",
        token_label="API Token",
        token_help_url="https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account",
    ),
    # Marketing & Ads
    "google_ads": OAuthProvider(
        key="google_ads",
        display_name="Google Ads",
        category="marketing",
        icon="🎯",
        description="Campaign management, metrics, and ad creation.",
        auth_kind="token",
        token_label="Developer Token",
        token_help_url="https://developers.google.com/google-ads/api/docs/first-call/dev-token",
    ),
    "snapchat_ads": OAuthProvider(
        key="snapchat_ads",
        display_name="Snapchat Ads",
        category="social",
        icon="👻",
        description="Campaign creation and performance insights.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://developers.snap.com/api/marketing-api/gettingstarted",
    ),
    "reddit_ads": OAuthProvider(
        key="reddit_ads",
        display_name="Reddit Ads",
        category="social",
        icon="🔴",
        description="Campaign creation and community targeting.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://ads-api.reddit.com/docs/",
    ),
    "semrush": OAuthProvider(
        key="semrush",
        display_name="Semrush",
        category="marketing",
        icon="🔍",
        description="SEO, keyword research, and competitive analysis.",
        auth_kind="token",
        token_label="API Key",
        token_help_url="https://www.semrush.com/api-management/",
    ),
    "ahrefs": OAuthProvider(
        key="ahrefs",
        display_name="Ahrefs",
        category="marketing",
        icon="🔗",
        description="Backlink analysis and keyword research.",
        auth_kind="token",
        token_label="API Token",
        token_help_url="https://ahrefs.com/api",
    ),
    # E-commerce & Payments
    "paypal": OAuthProvider(
        key="paypal",
        display_name="PayPal",
        category="ecommerce",
        icon="💰",
        description="Payment processing and transaction management.",
        auth_kind="token",
        token_label="Client ID:Secret",
        token_help_url="https://developer.paypal.com/dashboard/applications",
    ),
    "quickbooks": OAuthProvider(
        key="quickbooks",
        display_name="QuickBooks",
        category="finance",
        icon="📚",
        description="Accounting, invoicing, and financial management.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://developer.intuit.com/app/developer/qbo/docs/get-started",
    ),
    "squarespace": OAuthProvider(
        key="squarespace",
        display_name="Squarespace",
        category="ecommerce",
        icon="🟥",
        description="Store management and order processing.",
        auth_kind="token",
        token_label="API Key",
        token_help_url="https://developers.squarespace.com/commerce-apis",
    ),
    "wix": OAuthProvider(
        key="wix",
        display_name="Wix",
        category="ecommerce",
        icon="🌐",
        description="Store products and orders management.",
        auth_kind="token",
        token_label="API Key",
        token_help_url="https://dev.wix.com/docs/rest/",
    ),
    "bigcommerce": OAuthProvider(
        key="bigcommerce",
        display_name="BigCommerce",
        category="ecommerce",
        icon="🛒",
        description="E-commerce platform products and orders.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://developer.bigcommerce.com/docs/start/authentication",
    ),
    # Productivity & Design
    "microsoft_365": OAuthProvider(
        key="microsoft_365",
        display_name="Microsoft 365",
        category="productivity",
        icon="📧",
        description="Email, calendar, and productivity suite.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://learn.microsoft.com/en-us/graph/auth/",
    ),
    "typeform": OAuthProvider(
        key="typeform",
        display_name="Typeform",
        category="productivity",
        icon="📋",
        description="Forms, surveys, and response collection.",
        auth_kind="token",
        token_label="Personal Access Token",
        token_help_url="https://www.typeform.com/developers/get-started/personal-access-token/",
    ),
    "webflow": OAuthProvider(
        key="webflow",
        display_name="Webflow",
        category="design",
        icon="🎨",
        description="Site management and CMS collections.",
        auth_kind="token",
        token_label="API Token",
        token_help_url="https://developers.webflow.com/docs/getting-started",
    ),
    "framer": OAuthProvider(
        key="framer",
        display_name="Framer",
        category="design",
        icon="🖼️",
        description="Site publishing and project management.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://www.framer.com/developers/",
    ),
    "loom": OAuthProvider(
        key="loom",
        display_name="Loom",
        category="productivity",
        icon="🎥",
        description="Video recording and sharing.",
        auth_kind="token",
        token_label="API Key",
        token_help_url="https://dev.loom.com/",
    ),
    # Analytics & Data
    "segment": OAuthProvider(
        key="segment",
        display_name="Segment",
        category="analytics",
        icon="📊",
        description="Customer data platform sources and destinations.",
        auth_kind="token",
        token_label="Write Key",
        token_help_url="https://segment.com/docs/connections/find-writekey/",
    ),
    "amplitude": OAuthProvider(
        key="amplitude",
        display_name="Amplitude",
        category="analytics",
        icon="📈",
        description="Product analytics and event tracking.",
        auth_kind="token",
        token_label="API Key:Secret",
        token_help_url="https://www.docs.developers.amplitude.com/analytics/find-api-credentials/",
    ),
    "google_calendar": OAuthProvider(
        key="google_calendar",
        display_name="Google Calendar",
        category="productivity",
        icon="📅",
        description="Calendar events and scheduling.",
        auth_kind="token",
        token_label="OAuth Access Token",
        token_help_url="https://developers.google.com/calendar/api/guides/auth",
    ),
    "aws": OAuthProvider(
        key="aws",
        display_name="AWS",
        category="infrastructure",
        icon="☁️",
        description="Cloud resources and metrics.",
        auth_kind="token",
        token_label="Access Key ID:Secret",
        token_help_url="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html",
    ),
    # POS Systems
    "petpooja": OAuthProvider(
        key="petpooja",
        display_name="Petpooja",
        category="restaurant",
        icon="🍽️",
        description="Indian restaurant POS — menu, orders, and billing.",
        auth_kind="token",
        token_label="API Key",
        token_help_url="https://pos.petpooja.com/developers",
    ),
    "clover": OAuthProvider(
        key="clover",
        display_name="Clover",
        category="restaurant",
        icon="🍀",
        description="Clover POS — payments, orders, inventory.",
        auth_kind="token",
        token_label="API Token",
        token_help_url="https://docs.clover.com/docs/getting-started",
    ),
    "lightspeed": OAuthProvider(
        key="lightspeed",
        display_name="Lightspeed",
        category="restaurant",
        icon="⚡",
        description="Lightspeed POS — retail and restaurant management.",
        auth_kind="token",
        token_label="API Key",
        token_help_url="https://developers.lightspeedhq.com/",
    ),
    "revel": OAuthProvider(
        key="revel",
        display_name="Revel Systems",
        category="restaurant",
        icon="🖥️",
        description="Revel iPad POS — orders, reports, CRM.",
        auth_kind="token",
        token_label="API Key",
        token_help_url="https://developers.revelup.com/",
    ),
    "chownow": OAuthProvider(
        key="chownow",
        display_name="ChowNow",
        category="restaurant",
        icon="🥡",
        description="Online ordering for restaurants.",
        auth_kind="token",
        token_label="API Key",
        token_help_url="https://get.chownow.com/api",
    ),
    "ordermark": OAuthProvider(
        key="ordermark",
        display_name="Ordermark",
        category="restaurant",
        icon="📦",
        description="Delivery aggregation and order management.",
        auth_kind="token",
        token_label="API Key",
        token_help_url="https://ordermark.com/developers",
    ),
    "slice": OAuthProvider(
        key="slice",
        display_name="Slice",
        category="restaurant",
        icon="🍕",
        description="Pizza delivery platform and POS.",
        auth_kind="token",
        token_label="API Key",
        token_help_url="https://slicelife.com/developers",
    ),
    # Zoho Suite
    "zoho_crm": OAuthProvider(
        key="zoho_crm",
        display_name="Zoho CRM",
        category="crm",
        icon="🧑‍💼",
        description="Zoho CRM — leads, contacts, deals, and pipelines.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://www.zoho.com/crm/developer/docs/api/v2/oauth-overview.html",
    ),
    "zoho_books": OAuthProvider(
        key="zoho_books",
        display_name="Zoho Books",
        category="finance",
        icon="📗",
        description="Zoho Books — invoicing, expenses, and accounting.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://www.zoho.com/books/api/v3/",
    ),
    "zoho_campaigns": OAuthProvider(
        key="zoho_campaigns",
        display_name="Zoho Campaigns",
        category="marketing",
        icon="📧",
        description="Zoho Campaigns — email marketing and automation.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://www.zoho.com/campaigns/help/api.html",
    ),
    "zoho_desk": OAuthProvider(
        key="zoho_desk",
        display_name="Zoho Desk",
        category="support",
        icon="🎫",
        description="Zoho Desk — customer support and ticketing.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://www.zoho.com/desk/api/overview.html",
    ),
    "zoho_inventory": OAuthProvider(
        key="zoho_inventory",
        display_name="Zoho Inventory",
        category="ecommerce",
        icon="📦",
        description="Zoho Inventory — stock, orders, and warehouses.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://www.zoho.com/inventory/api/v1/",
    ),
    "zoho_subscriptions": OAuthProvider(
        key="zoho_subscriptions",
        display_name="Zoho Subscriptions",
        category="finance",
        icon="🔄",
        description="Zoho Subscriptions — recurring billing and subscriptions.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://www.zoho.com/subscriptions/api/v1/",
    ),
    "zoho_projects": OAuthProvider(
        key="zoho_projects",
        display_name="Zoho Projects",
        category="productivity",
        icon="📊",
        description="Zoho Projects — project management and time tracking.",
        auth_kind="token",
        token_label="Access Token",
        token_help_url="https://www.zoho.com/projects/api/v3/",
    ),
}


PROVIDERS: dict[str, OAuthProvider] = {**_OAUTH, **_TOKEN}


def get_provider(key: str) -> OAuthProvider | None:
    return PROVIDERS.get(key)


def list_providers() -> list[OAuthProvider]:
    return list(PROVIDERS.values())


def provider_to_public(p: OAuthProvider) -> dict[str, Any]:
    return {
        "key": p.key,
        "display_name": p.display_name,
        "scopes": list(p.scopes),
        "auth_kind": p.auth_kind,
        "category": p.category,
        "icon": p.icon,
        "description": p.description,
        "token_label": p.token_label if p.auth_kind == "token" else None,
        "token_help_url": p.token_help_url if p.auth_kind == "token" else None,
        "coming_soon": p.coming_soon,
    }
